name = "bubble-vote"
main = "worker.ts"
compatibility_date = "2026-08-12"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "bubble-vote-db"
database_id = "eb2ac2a9-7119-498d-9652-95494258ccb2"
