import './style.css';

type Game = { id: number; arena_id?: number; title: string; platform: 'PS1' | 'PS3' | 'SEGA'; genre: string; submitted_by: string; votes: number };
type Arena = { id: number; name: string; description: string; owner_username: string; game_count: number; vote_count: number };
type User = { id: number; username: string };

let games: Game[] = [];
let arenas: Arena[] = [];
let user: User | null = null;
let activeArena = 1;
let filter = 'ALL';
let localMode = false;
let language: 'fa' | 'en' = localStorage.getItem('bv_language') === 'en' ? 'en' : 'fa';
const app = document.querySelector<HTMLDivElement>('#app')!;
const max = () => Math.max(...games.map(g => g.votes), 1);
const esc = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]!));
function notice(message: string, tone: 'error' | 'info' = 'info') {
  document.querySelector('.notice')?.remove();
  const item = document.createElement('div'); item.className = `notice ${tone}`; item.textContent = message;
  document.body.appendChild(item); window.setTimeout(() => item.remove(), 4200);
}
function readLocal<T>(key: string, fallbackValue: T): T { try { return JSON.parse(localStorage.getItem(key) || 'null') ?? fallbackValue; } catch { return fallbackValue; } }
function writeLocal(key: string, value: unknown) { localStorage.setItem(key, JSON.stringify(value)); }
function localGames() { return readLocal<Game[]>(`bv_games_${activeArena}`, []); }
function localUsers() { return readLocal<Array<User & { password: string }>>('bv_users', []); }
const translations: Record<string, string> = {
  'PLAY / VOTE': 'بازی / رأی', 'The Arena': 'میدان رأی', 'How it works': 'چطور کار می‌کند', 'Log in / Register': 'ورود / ثبت‌نام', 'Add a game': 'افزودن بازی',
  'CURRENT ARENA': 'میدان فعلی', 'No arena yet': 'هنوز میدانی وجود ندارد', 'Create the first community arena': 'اولین میدان جامعه را بسازید', 'admin: @—': 'مدیر: —', '+ New arena': '+ میدان جدید',
  'COMMUNITY RANKINGS': 'رتبه‌بندی جامعه', 'LIVE': 'زنده', 'What deserves': 'کدام بازی شایسته', 'another round?': 'یک دور دیگر است؟', 'Drop a classic. Cast a vote. Watch the legends grow.': 'یک بازی خاطره‌انگیز اضافه کنید، رأی بدهید و رشد افسانه‌ها را ببینید.', 'Your next replay is one bubble away.': 'بازی بعدی شما فقط یک حباب فاصله دارد.',
  'All systems': 'همه سیستم‌ها', 'SORTED BY': 'مرتب‌سازی بر اساس', 'POPULARITY ↓': 'محبوبیت ↓', 'EMPTY ARENA': 'میدان خالی است', 'Your first bubble': 'اولین حباب شما', 'starts here.': 'از اینجا شروع می‌شود.', 'Create the first arena': 'ساخت اولین میدان',
  'THE VIBE': 'حال‌وهوای میدان', 'Every vote': 'هر رأی', 'makes it': 'آن را', 'bigger.': 'بزرگ‌تر می‌کند.', '+ Add to the arena': '+ افزودن به میدان', 'PlayStation 1': 'پلی‌استیشن ۱', 'PlayStation 3': 'پلی‌استیشن ۳', 'Sega': 'سگا',
  'THREE MOVES': 'سه حرکت', 'Make the': 'نسل', 'next classic.': 'کلاسیک بعدی را بسازید.', 'Register': 'ثبت‌نام', 'Create one simple account to join the community.': 'برای پیوستن به جامعه یک حساب بسازید.', 'Vote once': 'یک بار رأی بدهید', 'Each device can vote once for each game.': 'هر دستگاه برای هر بازی فقط یک بار رأی می‌دهد.', 'Grow': 'رشد', 'Arena admins curate; the community decides.': 'مدیران میدان انتخاب می‌کنند؛ جامعه تصمیم می‌گیرد.',
  'NEW CONTENDER': 'رقیب جدید', 'Only this arena\'s admin can add contenders.': 'فقط مدیر این میدان می‌تواند بازی اضافه کند.', 'GAME TITLE': 'نام بازی', 'SYSTEM': 'سیستم', 'GENRE': 'سبک', 'OPTIONAL': 'اختیاری', 'Join the arena': 'به میدان بپیوندید', 'Log in to vote. New here? Register below.': 'برای رأی دادن وارد شوید. تازه‌وارد هستید؟ ثبت‌نام کنید.', 'COMMUNITY ACCOUNT': 'حساب جامعه', 'USERNAME': 'نام کاربری', 'PASSWORD': 'رمز عبور', 'Log in': 'ورود', 'Log in ↗': 'ورود ↗', 'Register ↗': 'ثبت‌نام ↗', 'Need an account? Register': 'حساب ندارید؟ ثبت‌نام کنید', 'NEW COMMUNITY SPACE': 'فضای جدید جامعه', 'You become its admin and curate the games.': 'شما مدیر آن می‌شوید و بازی‌ها را انتخاب می‌کنید.', 'ARENA NAME': 'نام میدان', 'DESCRIPTION': 'توضیحات', 'Create arena': 'ساخت میدان', 'Create arena ↗': 'ساخت میدان ↗', 'Switch to English': 'English', 'Switch to Persian': 'فارسی'
};
function applyLanguage() {
  document.documentElement.lang = language === 'fa' ? 'fa' : 'en'; document.documentElement.dir = language === 'fa' ? 'rtl' : 'ltr';
  if (language === 'en') return;
  const walker = document.createTreeWalker(app, NodeFilter.SHOW_TEXT);
  let node: Node | null; while ((node = walker.nextNode())) { const value = node.textContent?.trim(); if (value && translations[value]) node.textContent = node.textContent!.replace(value, translations[value]); }
  app.querySelectorAll<HTMLInputElement>('input').forEach(input => { if (input.placeholder) input.placeholder = input.placeholder.replace('e.g. ', 'مثلاً '); });
}
function removeLegacyDemo() {
  const storedArenas = readLocal<Arena[]>('bv_arenas', []);
  const legacy = storedArenas.filter(a => a.name === 'The Classics' && a.owner_username === 'admin');
  if (legacy.length) { writeLocal('bv_arenas', storedArenas.filter(a => !legacy.includes(a))); legacy.forEach(a => localStorage.removeItem(`bv_games_${a.id}`)); }
}

function render() {
  const visible = games.filter(g => filter === 'ALL' || g.platform === filter).sort((a, b) => b.votes - a.votes);
  const arena = arenas.find(a => a.id === activeArena) || arenas[0];
  const arenaName = arena?.name || 'No arena yet';
  const arenaDescription = arena?.description || 'Create the first community arena';
  const arenaOwner = arena?.owner_username || '—';
  app.innerHTML = `<main><nav><div class="brand"><span class="logo">✦</span><span>PLAY / VOTE</span></div><div class="navlinks"><a class="active">The Arena</a><a href="#how">How it works</a></div><button class="language" id="language-toggle">${language === 'fa' ? 'English' : 'فارسی'}</button><button class="account" id="open-auth">${user ? `@${esc(user.username)} · Log out` : 'Log in / Register'}</button><button class="join ${user ? '' : 'disabled'}" id="open-add">Add a game <span>＋</span></button></nav>
  <section class="arena-picker"><div><span class="eyebrow">CURRENT ARENA</span><h2>${esc(arenaName)}</h2><p>${esc(arenaDescription)} · admin: @${esc(arenaOwner)}</p></div><div class="arena-actions">${arenas.length ? `<select id="arena-select">${arenas.map(a => `<option value="${a.id}" ${a.id === activeArena ? 'selected' : ''}>${esc(a.name)} · ${a.vote_count} votes</option>`).join('')}</select>` : ''}<button class="outline" id="open-arena">+ New arena</button></div></section>
  <section class="hero"><div class="eyebrow">COMMUNITY RANKINGS <i></i> LIVE</div><h1>What deserves<br><em>another round?</em></h1><p>Drop a classic. Cast a vote. Watch the legends grow.<br>Your next replay is one bubble away.</p><div class="stats"><strong>${games.length}</strong><span>games in the arena</span><b></b><strong>${games.reduce((n, g) => n + g.votes, 0).toLocaleString()}</strong><span>votes cast</span></div></section>
  <section class="toolbar"><div class="filters">${['ALL', 'PS1', 'PS3', 'SEGA'].map(p => `<button class="filter ${filter === p ? 'selected' : ''}" data-filter="${p}">${p === 'ALL' ? 'All systems' : p}</button>`).join('')}</div><span class="sort">SORTED BY <strong>POPULARITY ↓</strong></span></section>
  <section class="arena"><div class="bubble-field">${visible.length ? visible.map((g, i) => bubble(g, i)).join('') : '<div class="empty-state"><span class="eyebrow">EMPTY ARENA</span><h2>Your first bubble<br><em>starts here.</em></h2><p>Create an arena, then add the games your community wants to play.</p><button class="outline" id="open-empty-arena">+ Create the first arena</button></div>'}</div><aside><div class="side-label">THE VIBE</div><h2>Every vote<br>makes it <em>bigger.</em></h2><p>The more the community gets behind a game, the more it grows. Only the arena admin can add games; everyone with an account can vote once per device. Vote totals are public, voter names are private.</p><button class="outline" id="open-add-side">+ Add to the arena</button><div class="legend"><span><i class="dot ps1"></i> PlayStation 1</span><span><i class="dot ps3"></i> PlayStation 3</span><span><i class="dot sega"></i> Sega</span></div></aside></section>
  <section class="how" id="how"><div><span class="eyebrow">THREE MOVES</span><h2>Make the<br><em>next classic.</em></h2></div><div class="steps"><div><b>01</b><strong>Register</strong><p>Create one simple account to join the community.</p></div><div><b>02</b><strong>Vote once</strong><p>Each device can vote once for each game.</p></div><div><b>03</b><strong>Grow</strong><p>Arena admins curate; the community decides.</p></div></div></section></main><div class="modal hidden" id="modal"><form id="add-form"><button type="button" class="close" id="close">×</button><span class="eyebrow">NEW CONTENDER</span><h2>Add a game</h2><p>Only this arena's admin can add contenders.</p><label>GAME TITLE<input name="title" required placeholder="e.g. Castlevania: Symphony of the Night"></label><label>SYSTEM<select name="platform"><option>PS1</option><option>PS3</option><option>SEGA</option></select></label><label>GENRE <small>OPTIONAL</small><input name="genre" placeholder="e.g. RPG, racing, action"></label><button class="submit" type="submit">Add to the arena <span>↗</span></button></form></div><div class="modal hidden" id="auth-modal"><form id="auth-form"><button type="button" class="close" id="auth-close">×</button><span class="eyebrow">COMMUNITY ACCOUNT</span><h2>Join the arena</h2><p id="auth-copy">Log in to vote. New here? Register below.</p><label>USERNAME<input name="username" required minlength="3"></label><label>PASSWORD<input name="password" type="password" required minlength="8"></label><button class="submit" type="submit" id="auth-submit">Log in <span>↗</span></button><button type="button" class="auth-switch" id="auth-switch">Need an account? Register</button></form></div><div class="modal hidden" id="arena-modal"><form id="arena-form"><button type="button" class="close" id="arena-close">×</button><span class="eyebrow">NEW COMMUNITY SPACE</span><h2>Create an arena</h2><p>You become its admin and curate the games.</p><label>ARENA NAME<input name="name" required placeholder="e.g. Best RPGs ever"></label><label>DESCRIPTION<input name="description" placeholder="What is this arena about?"></label><button class="submit" type="submit">Create arena <span>↗</span></button></form></div>`;
  document.querySelectorAll<HTMLButtonElement>('[data-filter]').forEach(b => b.onclick = () => { filter = b.dataset.filter!; render(); });
  document.querySelectorAll('#open-add, #open-add-side').forEach(b => b.addEventListener('click', () => document.querySelector('#modal')?.classList.remove('hidden')));
  document.querySelector('#open-auth')?.addEventListener('click', () => user ? logout() : document.querySelector('#auth-modal')?.classList.remove('hidden'));
  document.querySelector('#language-toggle')?.addEventListener('click', () => { language = language === 'fa' ? 'en' : 'fa'; localStorage.setItem('bv_language', language); render(); });
  document.querySelector('#open-arena')?.addEventListener('click', () => document.querySelector('#arena-modal')?.classList.remove('hidden'));
  document.querySelector('#open-empty-arena')?.addEventListener('click', () => document.querySelector('#arena-modal')?.classList.remove('hidden'));
  document.querySelector('#arena-select')?.addEventListener('change', e => { activeArena = Number((e.target as HTMLSelectElement).value); history.replaceState(null, '', `?arena=${activeArena}`); loadGames(); });
  document.querySelector('#close')?.addEventListener('click', closeModal); document.querySelector('#modal')?.addEventListener('click', e => { if (e.target === e.currentTarget) closeModal(); });
  document.querySelector('#add-form')?.addEventListener('submit', addGame);
  document.querySelector('#auth-form')?.addEventListener('submit', auth);
  document.querySelector('#arena-form')?.addEventListener('submit', createArena);
  document.querySelector('#auth-switch')?.addEventListener('click', () => { const b = document.querySelector('#auth-submit')!; b.textContent = b.textContent?.startsWith('Register') ? 'Log in ↗' : 'Register ↗'; });
  ['auth-close', 'arena-close'].forEach(id => document.querySelector(`#${id}`)?.addEventListener('click', () => document.querySelector(`#${id === 'auth-close' ? 'auth-modal' : 'arena-modal'}`)?.classList.add('hidden')));
  document.querySelectorAll<HTMLButtonElement>('.vote').forEach(b => b.onclick = () => vote(Number(b.dataset.id)));
  document.querySelectorAll<HTMLElement>('.bubble').forEach(bubbleEl => {
    bubbleEl.addEventListener('pointermove', event => {
      if (window.matchMedia('(pointer: coarse)').matches) return;
      const rect = bubbleEl.getBoundingClientRect();
      const x = ((event.clientX - rect.left) / rect.width - 0.5) * 18;
      const y = ((event.clientY - rect.top) / rect.height - 0.5) * 18;
      bubbleEl.style.setProperty('--mx', `${x}px`); bubbleEl.style.setProperty('--my', `${y}px`);
    });
    bubbleEl.addEventListener('pointerleave', () => { bubbleEl.style.setProperty('--mx', '0px'); bubbleEl.style.setProperty('--my', '0px'); });
  });
  applyLanguage();
}
function bubble(g: Game, i: number) { const size = Math.round(122 + (g.votes / max()) * 112); return `<article class="bubble ${g.platform.toLowerCase()}" style="--bubble-size:${size}px;--delay:${i * -0.45}s"><div class="bubble-inner"><span class="platform">${g.platform}</span><h3>${esc(g.title)}</h3><span class="genre">${esc(g.genre)}</span><button class="vote" data-id="${g.id}">♥ <b>${g.votes}</b></button></div></article>`; }
function closeModal() { document.querySelector('#modal')?.classList.add('hidden'); }
async function addGame(e: Event) { e.preventDefault(); if (!user) { notice('Please log in before adding a game.', 'error'); return document.querySelector('#auth-modal')?.classList.remove('hidden'); } const data = Object.fromEntries(new FormData(e.target as HTMLFormElement)); if (localMode) { const arena = arenas.find(a => a.id === activeArena); if (arena?.owner_username !== user.username) return notice('Only this arena admin can add games.', 'error'); games.push({ id: Date.now(), arena_id: activeArena, title: String(data.title), platform: String(data.platform) as Game['platform'], genre: String(data.genre || 'Other'), submitted_by: user.username, votes: 0 }); writeLocal(`bv_games_${activeArena}`, games); closeModal(); return render(); } const response = await fetch(`/api/arenas/${activeArena}/games`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!response.ok) return notice((await response.json() as { error: string }).error, 'error'); closeModal(); loadGames(); }
async function vote(id: number) { if (localMode) { const voted = readLocal<number[]>('bv_device_votes', []); if (voted.includes(id)) return notice('این دستگاه قبلاً برای این بازی رأی داده است.', 'error'); const game = games.find(g => g.id === id); if (game) game.votes++; writeLocal('bv_device_votes', [...voted, id]); writeLocal(`bv_games_${activeArena}`, games); return render(); } const response = await fetch(`/api/games/${id}/vote`, { method: 'POST' }); if (!response.ok) return notice((await response.json() as { error: string }).error, 'error'); const game = games.find(g => g.id === id); if (game) game.votes++; render(); }
async function auth(e: Event) { e.preventDefault(); const form = e.target as HTMLFormElement; const values = Object.fromEntries(new FormData(form)); const register = document.querySelector<HTMLButtonElement>('#auth-submit')?.textContent?.startsWith('Register'); if (localMode) { const users = localUsers(); const username = String(values.username).trim(); const password = String(values.password); if (username.length < 3 || password.length < 8) return alert('Username needs 3+ characters and password needs 8+ characters.'); if (register) { if (users.some(u => u.username.toLowerCase() === username.toLowerCase())) return alert('That username is already taken.'); const newUser = { id: Date.now(), username, password }; writeLocal('bv_users', [...users, newUser]); user = { id: newUser.id, username }; } else { const found = users.find(u => u.username.toLowerCase() === username.toLowerCase() && u.password === password); if (!found) return alert('Incorrect username or password.'); user = { id: found.id, username: found.username }; } writeLocal('bv_session', user); document.querySelector('#auth-modal')?.classList.add('hidden'); return render(); } const response = await fetch(`/api/auth/${register ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); const data = await response.json() as { error?: string; user: User }; if (!response.ok) return alert(data.error); user = data.user; document.querySelector('#auth-modal')?.classList.add('hidden'); render(); }
async function logout() { if (localMode) localStorage.removeItem('bv_session'); else await fetch('/api/auth/logout', { method: 'POST' }); user = null; render(); }
async function createArena(e: Event) { e.preventDefault(); if (!user) return document.querySelector('#auth-modal')?.classList.remove('hidden'); const values = Object.fromEntries(new FormData(e.target as HTMLFormElement)); if (localMode) { const arena: Arena = { id: Date.now(), name: String(values.name), description: String(values.description || 'A community voting arena'), owner_username: user.username, game_count: 0, vote_count: 0 }; arenas = [...arenas, arena]; writeLocal('bv_arenas', arenas); document.querySelector('#arena-modal')?.classList.add('hidden'); activeArena = arena.id; return loadGames(); } const response = await fetch('/api/arenas', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) }); const data = await response.json() as { error?: string; id: number }; if (!response.ok) return alert(data.error); document.querySelector('#arena-modal')?.classList.add('hidden'); await loadArenas(); activeArena = data.id; await loadGames(); }
async function loadArenas() { if (localMode) { arenas = readLocal<Arena[]>('bv_arenas', arenas); activeArena = Number(new URLSearchParams(location.search).get('arena')) || arenas[0]?.id || 1; return; } try { const response = await fetch('/api/arenas'); if (response.ok) { const data = await response.json() as { arenas: Arena[] }; if (data.arenas?.length) arenas = data.arenas; activeArena = Number(new URLSearchParams(location.search).get('arena')) || arenas[0]?.id || 1; } } catch { localMode = true; arenas = readLocal<Arena[]>('bv_arenas', arenas); activeArena = Number(new URLSearchParams(location.search).get('arena')) || arenas[0]?.id || 1; } }
async function loadGames() { if (localMode) { games = localGames(); return render(); } try { const response = await fetch(`/api/arenas/${activeArena}/games`); if (response.ok) { const data = await response.json() as { games: Game[] }; if (data.games?.length) games = data.games; } } catch { localMode = true; games = localGames(); } render(); }
async function load() { try { const me = await fetch('/api/auth/me'); if (!me.ok) throw new Error('local'); user = (await me.json() as { user: User | null }).user; } catch { localMode = true; user = readLocal<User | null>('bv_session', null); } await loadArenas(); await loadGames(); }
removeLegacyDemo();
load();
